name: Build iOS
# https://github.com/actions/virtual-environments

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

env:
    DOTNETVERSION: 6.0.x

jobs:
  build-mac:
    runs-on: macos-12
    name: iOS Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.DOTNETVERSION}}
          include-prerelease: true

      - name: Install MAUI Workloads
        run: |
          dotnet workload install ios --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore src/FormulaGenerator.MAUI/FormulaGenerator.MAUI.csproj

      - name: Build MAUI iOS
        run: dotnet build src/FormulaGenerator.MAUI/FormulaGenerator.MAUI.csproj -c Release -f net6.0-ios --no-restore

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ios-ci-build
          path: src/FormulaGenerator.MAUI/bin/Release/net6.0-ios/**/*.app/
